### PR TITLE
Github Action for ctests

### PR DESCRIPTION
**Pull request by DJ2LS**
This is a first working workflow for running radae ctests on Github Actions  ( #1 ) . 
It will be triggered on "push" and should be working in every branch. 
There is possible support for multiple operating systems which could be added easily in future. 
I also decided testing against several latest python versions. Sometimes there are incompatibilities with newer versions, so the test might "warn" early enough if there is an possible problem with a specific python version. Also its common, users have different python versions installed. However, if not needed, this could be disabled easily. 

All tests need about 12minutes to complete.

Since all tests are passing, #22 can be closed as well

image

image

image

### CODE REVIEW

**Comment by drowe67** [comment]
Hi @DJ2LS - thank you so much for working on this one :slightly_smiling_face:  Interesting that it passed with the standard torch package, I have been installing from the [Torch](https://pytorch.org/get-started/locally) site to date.  I'm a bit busy with the day job for the next few days but will take a closer look and merge later in the week.

**Comment by DJ2LS** [comment]
You're welcome, @drowe67 ,but it was like every GitHub action work - a pain 😀 

https://pypi.org/project/torch/ provides the latest stable version.

**Comment by drowe67** [comment]
> @drowe67 meanwhile 24.04.1 LTS is available. I think we should add it to the test as well, even if its not part of the project scope, yet.

No.  The project scope is there to stop exactly this sort of distraction, so that we can maintain focus on what really matters.

**Comment by DJ2LS** [comment]
Understood 👍

I try to remove the remaining debugging code the next days.

**Comment by drowe67** [comment]
> Understood 👍
> 
> I try to remove the remaining debugging code the next days.

Sure, just tell me when it's ready to test & merge.  Hmm, how will I test if I pull from your repo?  If I `git push` I'm not sure if it will run the tests :thinking:

**Comment by DJ2LS** [comment]
> > Understood 👍
> > I try to remove the remaining debugging code the next days.
> 
> Sure, just tell me when it's ready to test & merge. Hmm, how will I test if I pull from your repo? If I `git push` I'm not sure if it will run the tests 🤔

you could push to my fork of radae, then having a look at actions and check if they are failing:

https://github.com/DJ2LS/radae/tree/ls-github-action

Another option would be, merging, and if you have stability concerns, you could disable it via Github Actions. This PR shouldnt affect the code itself, as its a separated task.

**Comment by drowe67** [comment]
Thanks @DJ2LS - I'll merge and do any residual debugging in `main`

**Pull request merged**
